import { contextBridge, ipcRenderer } from 'electron';
import type { OutpostBridge } from '../shared/contracts';

const bridge: OutpostBridge = {
  getBootstrap: () => ipcRenderer.invoke('outpost:get-bootstrap'),
  createProfile: (displayName) => ipcRenderer.invoke('outpost:create-profile', displayName),
  updateProfile: (displayName) => ipcRenderer.invoke('outpost:update-profile', displayName),
  refreshStorage: () => ipcRenderer.invoke('outpost:refresh-storage'),
  refreshHardware: () => ipcRenderer.invoke('outpost:refresh-hardware'),
  refreshModules: () => ipcRenderer.invoke('outpost:refresh-modules'),
  installModule: (moduleId) => ipcRenderer.invoke('outpost:install-module', moduleId),
  startModule: (moduleId) => ipcRenderer.invoke('outpost:start-module', moduleId),
  stopModule: (moduleId) => ipcRenderer.invoke('outpost:stop-module', moduleId),
  repairModule: (moduleId) => ipcRenderer.invoke('outpost:repair-module', moduleId),
  uninstallModule: (moduleId) => ipcRenderer.invoke('outpost:uninstall-module', moduleId),
  getLibraryStatus: () => ipcRenderer.invoke('outpost:get-library-status'),
  scanLibrary: () => ipcRenderer.invoke('outpost:scan-library'),
  removeKiwixContent: (contentId) => ipcRenderer.invoke('outpost:remove-kiwix-content', contentId),
  installKiwixSample: () => ipcRenderer.invoke('outpost:install-kiwix-sample'),
  getKiwixCatalogOptions: () => ipcRenderer.invoke('outpost:get-kiwix-catalog-options'),
  fetchKiwixCatalog: (query, language, category, startIndex) => ipcRenderer.invoke('outpost:fetch-kiwix-catalog', query, language, category, startIndex),
  downloadKiwixContent: (entryId) => ipcRenderer.invoke('outpost:download-kiwix-content', entryId),
  getKiwixDownloadStatus: () => ipcRenderer.invoke('outpost:get-kiwix-download-status'),
  cancelKiwixDownload: () => ipcRenderer.invoke('outpost:cancel-kiwix-download'),
  getDocumentLibrary: () => ipcRenderer.invoke('outpost:get-document-library'),
  importDocuments: () => ipcRenderer.invoke('outpost:import-documents'),
  scanDocuments: () => ipcRenderer.invoke('outpost:scan-documents'),
  getDocument: (documentId) => ipcRenderer.invoke('outpost:get-document', documentId),
  getDocumentText: (documentId) => ipcRenderer.invoke('outpost:get-document-text', documentId),
  searchDocuments: (query) => ipcRenderer.invoke('outpost:search-documents', query),
  updateDocumentMetadata: (documentId, update) => ipcRenderer.invoke('outpost:update-document-metadata', documentId, update),
  removeDocument: (documentId) => ipcRenderer.invoke('outpost:remove-document', documentId),
  addDocumentBookmark: (documentId, page, label) => ipcRenderer.invoke('outpost:add-document-bookmark', documentId, page, label),
  removeDocumentBookmark: (documentId, bookmarkId) => ipcRenderer.invoke('outpost:remove-document-bookmark', documentId, bookmarkId),
  saveDocumentNote: (documentId, note) => ipcRenderer.invoke('outpost:save-document-note', documentId, note),
  removeDocumentNote: (documentId, noteId) => ipcRenderer.invoke('outpost:remove-document-note', documentId, noteId),
  saveDocumentAnnotation: (documentId, annotation) => ipcRenderer.invoke('outpost:save-document-annotation', documentId, annotation),
  removeDocumentAnnotation: (documentId, annotationId) => ipcRenderer.invoke('outpost:remove-document-annotation', documentId, annotationId),
  checkForUpdates: () => ipcRenderer.invoke('outpost:check-updates'),
  downloadUpdate: () => ipcRenderer.invoke('outpost:download-update'),
  applyUpdate: () => ipcRenderer.invoke('outpost:apply-update'),
  prepareForRemoval: () => ipcRenderer.invoke('outpost:prepare-removal'),
};

contextBridge.exposeInMainWorld('outpost', bridge);
